# .github/workflows/release.yml
name: Semantic Release POC

on:
  push:
    branches:
      - main
      - staging
      - development

jobs:
  release:
    name: Create Release / Pre-release
    runs-on: ubuntu-latest
    permissions:
      contents: write          # To push commits, tags, and create/update CHANGELOG.md
      issues: write            # To comment on issues linked to commits
      pull-requests: write     # To comment on PRs linked to commits
      # packages: write        # If publishing to GitHub Packages (needed by @semantic-release/github if it tries this)
    # outputs: # Outputs are less critical if no subsequent deploy jobs in this POC
      # new_release_published: ${{ steps.semantic.outputs.new_release_published }}
      # new_release_version: ${{ steps.semantic.outputs.new_release_version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0       # IMPORTANT: Fetches all history and tags for semantic-release

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'      

      - name: Install dependencies
        run: npm ci

      - name: Run semantic-release
        id: semantic # Give the step an ID if you were to use its outputs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release