name: semantic-release

on:
  push:
    branches: [ main, staging, development ]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-node@v4
        with: { node-version: '20', cache: 'npm' }

      - run: npm ci

      - name: semantic-release
        id: sr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
        run: npx semantic-release

      # Collapse RC headings after GA tag lands on main
      - name: Collapse stage headings
        if: ${{ github.ref_name == 'main' && steps.sr.outputs.new_release_published == 'true' }}
        run: |
          sed -i '/-stage\./d' CHANGELOG.md
          git config user.name  sync-bot
          git config user.email sync-bot@users.noreply.github.com
          git add CHANGELOG.md
          git commit -m "chore(changelog): collapse RC entries [skip ci]" || echo "nothing to collapse"
          git push